### PR TITLE
Japanese geoid GSIGEO2011 v2.1

### PR DESCRIPTION
**Pull request by hernando**
This PR adds a grid file the Japanese geoid GSIGEO2011. As explained in jp_gsi_README.txt only a portion of the original data has been considered as I failed to find a proper vertical CRS for some archipelagos.
I've made a draft PR because a colleague of mine of trying to figure out the exact. I've seen the two threads mentioned in #36, but they don't seem to say anything about the 
Regarding the validation, I checked that the transformation from EPSG:6667 to EPSG:6668+6695 works in PROJ after adding it to proj.db and compared the altitude of one coordinate using Google maps.  The only "official" point I could find for validation is the default values displayed in this converter: https://vldb.gsi.go.jp/sokuchi/surveycalc/surveycalc/transf.html (which I thought I could use to double check a few more points, but it takes the geoid data as input). For those values, I get a difference of 6cm, which seems a bit high to me for not having done an interpolation in the creation of the grid (an open question is which version of the geoid was used for the default values). An alternative that I have to explore is to compile the Fortran program that comes with the data and try to use it.

### CODE REVIEW

**Comment by hernando** [comment]
I have removed the grid file until I have a confirmation that there's no copyright violation. The original file may not covered by the "Geospatial Information Authority of Japan Website Terms of Use".

**Comment by hernando** [comment]
Closed due to limitations in the distribution of the data from GSI. More details here: https://github.com/OSGeo/PROJ-data/issues/36#issuecomment-650187244
@rouault, do you think the script for converting the the ASCII file from GSI into a valid .tif file for proj is still a valuable contribution?

**Comment by rouault** [comment]
I have asked to a contact who has a contact at GSI to reach them to see if they can help us clear things. I was thinking more on making sure the conversion was OK regarding test points, but maybe they can help clarifying/improving licensing

**Comment by hernando** [comment]
OK, once we have clearance I will reopen the PR.

**Comment by hernando** [comment]
For validation this online calculator could be used: https://vldb.gsi.go.jp/sokuchi/surveycalc/geoid/calcgh/calcframe.html

**Comment by rouault** [comment]
Below an answer from Tatsuya Yamashita at GSI:

"""
Hi, Even, 

Thank you for basic information about your activities and clarifying what you would like to know. 

I asked Shinobu Kurihara, who is responsible for geoid datasets in GSI, about your questions. 
As for a terms of use and a license of GSIGEO2011, the users are supposed to follow "terms of use for GSI web contents". 
 https://www.gsi.go.jp/kikakuchousei/kikakuchousei40182.html
Unfortunately it is written in Japanese (please use a google translator if necessary), but the main points are: 
 * Users can use (e.g. copy) the contents if following the terms of use, and no matter if it is commercial-use. 
 * The terms of use asks users to follow seven rules, such as a reference to URL of web contents in README, etc. 
 * A license of the terms of use is compatible with CC BY v4.0. It means the web contents to which terms of use for GSI web contents is applied can be also used by following CC BY. 
 * However, if the users utilize the web contents for surveying by local government or cadastral surveying, they need to ask permission from GSI. 

And as for the second question, GSI online converter is also based on simple bilinear interpolation (except on grid points and grid lines), probably just as your program. 
In addition, both GSIGEO2011 download file and the file used by the converter are the latest version (gsigeo2011_ver2_1.asc). 
We recognize the small difference between the results obtained from the online converter and that obtained using the interpolator included in GSIGEO2011 download file, which is due to round-off error. 
Thus if you find difference in the smallest digit, it is possibly the round-off error. 
But otherwise, further investigation will be required. 

If you (and Juan) require more detailed information, then please free to ask Shinobu (***redacted , please ask me, Even Rouault, in private if you need the email *** ) and me. 

I'm glad if my comments are helpful for you. 

Best regards, 
Tatsuya
"""

**Comment by hernando** [comment]
That's the page that was already linked in [this comment](https://github.com/OSGeo/PROJ-data/issues/36#issuecomment-649589663). The English version says:
"Regarding the application for duplication and use of Public Survey Results based on Survey Act, you must obtain approval from the Survey Planning Organization that has developed the concerned Survey Results. With regard to the results developed by GSI, approval from GSI is needed."
As I understand it, permission is necessary to redistribute (duplication) the geoid and even if it wasn't, the final license wouldn't be CC BY v4.0 compatible as users of the grid must request permission to GSI to use it. Or am I interpreting this wrongly?

Regarding the validation, I took some points from the online tool posted above and this is what I obtained:

    Lat     Lon      geoid h (m) reference error (mm)
    34.290  135.630  39.861751   39.8601    1.65
    36.103  140.087  40.180027   40.1817   -1.67
    43.217  143.129  30.636525   30.6389    2.37
    38.675  139.886  40.129904   40.1281    1.80
    36.344  137.654  42.895498   42.8956   -0.10
    33.179  130.063  32.303586   32.3036   -1.40
    39.801  141.322  41.886693   41.8862    0.49

    The RMS is 0.9471 mm.

All inputs are in JGD2011 EPSG:6667

**Comment by rouault** [comment]
> As I understand it, permission is necessary to redistribute (duplication) the geoid and even if it wasn't, the final license wouldn't be CC BY v4.0 compatible as users of the grid must request permission to GSI to use it. Or am I interpreting this wrongly?

I don't know. That's a bit confusing indeed. Drop me an email at even.rouault at spatialys.com and I'll forward you the contacts at GSI so they can hopefully clarify things

**Pull request closed without merging**
