### PR TITLE
NN1954 and NN2000 added to PROJ-data

### PR DESCRIPTION
**Pull request by himsve**

### CODE REVIEW

**Comment by rouault** [comment]
Looks quite close to be ready: Two small observations valid for the 2 tiff files:
- a warning to address if possible: "TIFF tag DateTime malformed. Should be YYYY:MM:DD HH:MM:SS"
- Could I suggest to put the CRS names as well as the CRS code in TIFFTAG_IMAGEDESCRIPTION, like done for other grids ? For example instead of "EPSG:4937 to EPSG:5941. Converted from HREF2018B_NN2000_EUREF89.gtx." --> "EPSG:4937 (ETRS89) to EPSG:5941 (NN2000 height). Converted from HREF2018B_NN2000_EUREF89.gtx."

**Comment by rouault** [comment]
Anything left on your side ? This looks good to me otherwise

**Comment by meastp** [comment]
@himsve @rouault Is this ready to merge now? :)

**Comment by rouault** [comment]
> Is this ready to merge now? :)

The PR should be rebased on top of current master. There are conflicts in some generated files

**Pull request merged**
