### PR TITLE
Hungarian grids

### PR DESCRIPTION
**Pull request by zsiki**
Dear Developers,

we have registered EPSG codes for Hungarian grids:

EPSG: 10668 Horizontal transformation
EPSG: 10666 Geoid model
EPSG: 10667 Reversible geoid model

This pull request adds our grids and updates proj-data pages.

Tanks,
Zoltan

### CODE REVIEW

**Comment by rouault** [comment]
I've noticed a discrepency on the licensing. In copyright_and_licenses.csv and hu_bme_README.txt, you mention [Creative Commons Attribution 4.0 BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) but in the TIFFTAG_COPYRIGHT of the TIFF files, Creative Commons Attribution 4.0 https://creativecommons.org/licenses/by/4.0/ is mentionned.
They are not the same. The later (CC-BY-4.0) is less restrictive than (CC-BY-SA-4.0), because it doesn't have the share-alike restriction. Both are fine for PROJ, you just need to decide which one.

Small remarks. In hu_bme_hd72corr.tif,  the value of TIFFTAG_IMAGEDESCRIPTION is "HD72 (EPSG:4237) to ETRF2000 (EPSG:9067). Converted from ntv2_0.gsb".  The " Converted from ntv2_0.gsb" is a bit weird since this is the name of the original Canadian NTV2 grid. I assume your source NTV2 file was named differently. The grid_name=XXX  metadata item in the same file is also a bit weird. It would be best not to include it, although that's not a big deal.

**Comment by jjimenezshaw** [comment]
Do you know that it has to be complemented with changes in https://github.com/OSGeo/PROJ/blob/master/data/sql/grid_alternatives.sql ? Otherwise PROJ will not recognize those files.

**Comment by zsiki** [comment]
> I've noticed a discrepency on the licensing. In copyright_and_licenses.csv and hu_bme_README.txt, you mention [Creative Commons Attribution 4.0 BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) but in the TIFFTAG_COPYRIGHT of the TIFF files, Creative Commons Attribution 4.0 https://creativecommons.org/licenses/by/4.0/ is mentionned. They are not the same. The later (CC-BY-4.0) is less restrictive than (CC-BY-SA-4.0), because it doesn't have the share-alike clause. Both are fine for PROJ, you just need to decide which one.
> 
> Small remarks. In hu_bme_hd72corr.tif, the value of TIFFTAG_IMAGEDESCRIPTION is "HD72 (EPSG:4237) to ETRF2000 (EPSG:9067). Converted from ntv2_0.gsb". The " Converted from ntv2_0.gsb" is a bit weird since this is the name of the original Canadian NTV2 grid. I assume your source NTV2 file was named differently. The grid_name=XXX metadata item in the same file is also a bit weird. It would be best not to include it, although that's not a big deal.

I have corrected TIFFTAGs, I hope these are correct.

**Comment by zsiki** [comment]
> @zsiki gentle ping in case you didn't see our above messages

I've just added hu_bme grids to sql insert, sorry being late.

**Pull request merged**
