### PR TITLE
Prefix files with agencyname_ according to PROJ RFC5

### PR DESCRIPTION
**Pull request by rouault**
@kbevers @dalia2 You will be particularly interested by the second commit of this PR, e143c3f88082e820d1d87b920a5791ea0c352e19, that renames the init files you've submitted, and updates their content. I haven't checked more thorougly that it is OK...

What I can tell to @dalia2 is that there will probably need for follow-up work to merge together the ISN93_ISN2016.gsb+ISN93_ISN2016.gtx and ISN2004_ISN2016.gsb+ISN2004_ISN2016.gtx file in a single one (only the horizontal .gsb part has been converted to .tif. The .gtx part is only in the soon legacy proj-datumgrid repository for now). Not sure how that would fit in the types currently enumerated in https://github.com/OSGeo/PROJ/blob/master/docs/source/specifications/geodetictiffgrids.rst . Perhaps a TYPE=HORIZONTAL_AND_VERTICAL_OFFSET that could be used by both +proj=hgridshift and +proj=vgridshift, the first one using the first 2 samples, and the second one the 3rd samples ?

### CODE REVIEW

**Comment by kbevers** [comment]
> that renames the init files you've submitted, and updates their content. I haven't checked more thorougly that it is OK...

Will it still be possible to use them by running e.g. `cct DK:S34J` or should the full name be qualified with this name?

**Comment by rouault** [comment]
> should the full name be qualified with this name?

full qualified name only. Unless we hardcome something in PROJ

**Comment by kbevers** [comment]
> full qualified name only.

:-(

It's a different story with grids, right? As far as I have understood (and not got around to test yet), I can do `cct +proj=vgridshift +grids=dvr90.gtx` and it will automatically re-map `dvr90.gtx` to `dk_sdfe_dvr90.gtx`. Is that correct?

**Comment by rouault** [comment]
> :-(

I'll do it to make you happy again hopefully

> It's a different story with grids, right? As far as I have understood (and not got around to test yet), I can do cct +proj=vgridshift +grids=dvr90.gtx and it will automatically re-map dvr90.gtx to dk_sdfe_dvr90.gtx. Is that correct?

Yes (to dk_sdfe_dvr90.tif more exactly)

**Comment by kbevers** [comment]
> I'll do it to make you happy again hopefully

I wonder if the better solution is to move the init files to the PROJ repo and keep this one strictly for grids. We are working on getting everything in `DK` registered in EPSG so at some point in the future that file will be deprecated. The guys from Iceland should preferably work towards the same goal but that is of course up to them.

**Comment by rouault** [comment]
As you wish. I don't have a strong preference regarding this.
But we'll have non-grid files there at some point, like JSon master files from deformation models, maybe triangulation models, etc.

The -geotiff suffix of the repo might not be the best naming. I thought at -new, but @hobu was wise to point that the new of today is the old of tomorrow.

**Comment by kbevers** [comment]
> Yes (to dk_sdfe_dvr90.tif more exactly)

Of course. The magic behind this is the grid_alternatives table, yes? Would it work if we added init file alias to that table? Or would a init_alternatives table be needed?

> As you wish. I don't have a strong preference regarding this.

Just a suggestion, I am not sure it's the best way forward. Regarding the naming of the init files, one of the nice qualities of the current names is that they are super easy to both remember and type. And of course there's the issue of compatibility. At least the `DK` file has been out in the wild for a while now. 

I see a few ways to handle this:

1. Keep the user-facing `DK`, `NKG` and `ISL` filenames, rename the other init-files according to the `<country>_<agency>` pattern.
2. Employ a grid_alternatives type solution
3. Remap the init files to `proj.db` (I assume this is possible although I haven't got a clue as to how)
4. Stop distributing init-files altogether.

1 or 2 seems simplest. 3 is probably the best way (when excluding EPSG...) and 4 is probably best in the long term.

> The -geotiff suffix of the repo might not be the best naming. I thought at -new, but @hobu was wise to point that the new of today is the old of tomorrow.

How about renaming this repo `PROJ-resources`? or `PROJ-data`? Doesn't imply anything regarding the type of the content.

**Comment by rouault** [comment]
> The magic behind this is the grid_alternatives table, yes?

yes

> Would it work if we added init file alias to that table?

That could be done, but it is a bit of far stretching. As there are just at most 4 entries for which we'd need compatibility (excluding the historical nad27 and the like that are shipped through the PROJ data/ directory), hardcoding them in a static array could be the simplest solution.

> rename the other init-files

Which ones are you thinking too ? The existing ones in data/ ? I have no idea where they come from :-) 

> Remap the init files to proj.db (I assume this is possible although I haven't got a clue as to how)

Registering a transformation in the DB with a PROJ pipeline string is possible. See the AuthorityFactory_proj_based_transformation test in test/unit/test_factory.cpp.
Currently it would work with cs2cs SOURCE_CRS TARGET_CRS. If you want to directly reference the transformation object by its AUTH:CODE, it would need some tuning of cct to do the DB query.

> How about renaming this repo PROJ-resources? or PROJ-data?

PROJ-data would be fine to me.

**Comment by kbevers** [comment]
> Which ones are you thinking too ? The existing ones in data/ ? I have no idea where they come from :-)

The `DK_*.pol` and `FO_*.pol` files. They should ideally only ever be initialized via `+init=DK` or `+init=FO`. The old ones in `data/` can just stay as they are. Although we may want to consider removing them at some point in the future.

> Registering a transformation in the DB with a PROJ pipeline string is possible. See the AuthorityFactory_proj_based_transformation test in test/unit/test_factory.cpp.
Currently it would work with cs2cs SOURCE_CRS TARGET_CRS. If you want to directly reference the transformation object by its AUTH:CODE, it would need some tuning of cct to do the DB query.

I'll look into this. It seems promising. The `DK`, `FO` and `NKG` init-files are all build around a specific hub CRS, e.g. ETRS89 (EPSG:4258) for DK. The idea being that you can build a pipeline like `+proj=pipeline +step +proj=DK:UTM32N +inv +step +proj=DK:S34J`. Is PROJ clever enough to figure out how to combine two entries in `other_transformation` if they share a common CRS?

**Comment by kbevers** [comment]
> PROJ-data would be fine to me.

Feel free to change the name of the repo :)

**Comment by rouault** [comment]
> The `DK_*.pol` and `FO_*.pol` files

Ah of course :-) Well, maybe the simplest compromise for now would be to keep the DK etc init files with their current names, but still have DK_*.pol & FO_*.pol prefixed by country_agency ? So your 1. suggestion.
Or maybe drop completely this second commit if you see more drawbacks than advantages in it ? I just did it for consistency, but I don't really care.

> Is PROJ clever enough to figure out how to combine two entries in other_transformation if they share a common CRS?

It should be able to chain 2 transformations that have a common CRS, but this has only been tested with geodetic CRS (maybe vertical CRS as well ? not sure)
This is done by CoordinateOperationFactory::Private::findsOpsInRegistryWithIntermediate() that calls AuthorityFactory::createFromCRSCodesWithIntermediates()

**Comment by rouault** [comment]
> > PROJ-data would be fine to me.
> 
> Feel free to change the name of the repo :)

@hobu Does PROJ-data for this repository look good to you ?

**Comment by kbevers** [comment]
> Well, maybe the simplest compromise for now would be to keep the DK etc init files with their current names, but still have DK_.pol & FO_.pol prefixed by country_agency ? So your 1. suggestion.
Or maybe drop completely this second commit if you see more drawbacks than advantages in it ? I just did it for consistency, but I don't really care.

Compromise seems fine. I'll try to add the transformations to the DB. Ideally that means that we can remove at least the `DK`, `FO` and `NKG` files and just use the resourses from this repo, country and agency prefixes included.

> It should be able to chain 2 transformations that have a common CRS, but this has only been tested with geodetic CRS (maybe vertical CRS as well ? not sure)

Cool. I think I'll get the chance to test the verticalCRS case as well then. I'll let you know how it goes :)

**Comment by rouault** [comment]
> Compromise seems fine

Second commit modified according to 1. variant

**Pull request merged**
