### PR TITLE
Add a copyright_and_licenses.csv file to capture copyright & license information for distributed files

### PR DESCRIPTION
**Pull request by rouault**
@sebastic Does that include all you need for the purpose of Debian packaging ?

### CODE REVIEW

**Comment by sebastic** [comment]
It's mostly missing copyright years, only the copyright holders are documented.

**Comment by rouault** [comment]
> It's mostly missing copyright years

I'm not sure where we could find them. That would certainly be a very time consuming quest... Is that critical ? From what I can see in https://salsa.debian.org/debian-gis-team/proj-rdnap/blob/master/debian/copyright, some files have no copyright years
```
Files: Variant*/*
Copyright: Nederlandse Samenwerking Geodetische Infrastructuur (NSGI)
License: CC-BY-4.0
```

**Comment by sebastic** [comment]
If the agency supplies the copyright information it should be included.

How will multiple copyright holders be represented in the CSV?

**Comment by rouault** [comment]
> If the agency supplies the copyright information it should be included.

It was mentioned for the Swisstopo grids and I've added it for the files of National Land Survey of Iceland since it was in the README.

For files originating from NTv2 grids, where there is a field in the header with the last updated date, we could possibly use that as a likely copyright date ?

> How will multiple copyright holders be represented in the CSV?

Not sure. Perhaps using semi-colon (;) as a separator inside the field ?

**Comment by sebastic** [comment]
> For files originating from NTv2 grids, where there is a field in the header with the last updated date, we could possibly use that as a likely copyright date ?

No need to guess copyright dates, if its not supplied it can be left out.

>> How will multiple copyright holders be represented in the CSV?
> 
> Not sure. Perhaps using semi-colon (;) as a separator inside the field ?

Separating multiple copyright holders with semi-colons is a good option.

**Comment by rouault** [comment]
@kbevers Does that look good to you ?

**Comment by kbevers** [comment]
> @kbevers Does that look good to you ?

Yes

**Pull request merged**
