### PR TITLE
Add geoid grid fr_ign_RAF20.tif

### PR DESCRIPTION
**Pull request by p-assali**
Add the up to date **geoid grid for mainland France RAF20**.

For mainland France, the [RAF20 geoid grid](https://geodesie.ign.fr/index.php?page=grilles) was updated at the end of 2021 to take into account the maintenance operations of the RGF93 geodetic system.

Following [grid tools](https://github.com/OSGeo/PROJ-data/tree/master/grid_tools) have been used to produce and check the [Geodetic TIFF grid (GTG)](https://github.com/OSGeo/PROJ/blob/master/docs/source/specifications/geodetictiffgrids.rst) file :

- [vertoffset_grid_to_gtiff.py](https://github.com/OSGeo/PROJ-data/tree/master/grid_tools#converting-from-gtx-to-gtg)
- [check_gtiff_grid.py](https://github.com/OSGeo/PROJ-data/tree/master/grid_tools#checking-compliance-of-geotiff-files-with-the-gtg-specification)

### CODE REVIEW

**Comment by rouault** [comment]
See https://github.com/OSGeo/PROJ-data/blob/master/CONTRIBUTING.md for the other files to update (the version to indicate in the version_added column of copyright_and_licenses.csv will be 1.10)
Looking at the metadata of the GeoTIFF file, it should be amended. The geographic CRS to use should be EPSG:9781 for the 3D geographic CRS "RGF93 v2b" . See https://epsg.org/transformation_9876/RGF93-v2b-to-NGF-IGN69-height-5.html
A corresponding pull request to the https://github.com/OSGeo/PROJ repository would be appreciated to register the new grid (as indicated in the above mentioned CONTRIBUTING.md)

**Comment by rouault** [comment]
@p-assali quick remainder that this pull request needs follow-up to be integrated.
update w.r.t my previous comment: the version number will be 1.11 since 1.10 is about to be released

**Comment by rouault** [comment]
could you please drop the changes in files.geojson ? There are encoding issues and other suspicious changes. I'll regenerate that file on my side, once your PR is merged.

yes, a pull request to OSGeo/PROJ is needed so that the 'RAF20.tac' name in the EPSG dataset is bound to the fr_ign_RAF20.tif file. See https://github.com/OSGeo/PROJ/commit/098a661d7e57df71fddf064a55318df9cee4a280 for a very similar use case.
To check that it works properly, "projinfo -s EPSG:9781 -t EPSG:5720 -o PROJ" should display a PROJ string with the .tif filename in it.

**Comment by p-assali** [comment]
- [x] Changes in file `files.geojson` have been droped.
- [x] Dedicated pull request to OSGeo/PROJ to link `RAF20.tac` in the EPSG Dataset  to to corresponding `fr_ign_RAF20.tif` : [https://github.com/OSGeo/PROJ/pull/3228](https://github.com/OSGeo/PROJ/pull/3228)

**Pull request merged**
